CREATE DATABASE CHQA_BANHANG
GO
USE CHQA_BANHANG
GO
CREATE TABLE LoaiTaiKhoan
(
	MaLoai INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TenLoai NVARCHAR(50),
)
CREATE TABLE TaiKhoan
(
	MaTaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
	LoaiTaiKhoan INT FOREIGN KEY REFERENCES LoaiTaiKhoan(MaLoai),
	TenDangNhap NVARCHAR(50),
	MatKhau NVARCHAR(50),
)
CREATE TABLE NhaCungCap
(
	MaNCC VARCHAR(10) PRIMARY KEY NOT NULL, 
	TenNCC NVARCHAR(50),
	SDT CHAR(11), 
	Email VARCHAR(50),
)
CREATE TABLE SanPham
(
	MaSP NVARCHAR(10) PRIMARY KEY NOT NULL, 
	TenSP NVARCHAR(50),
	GiaBan FLOAT,
	GiaGoc FLOAT, 
	SoLuong INT,
	Size CHAR(3),
	TrangThai NVARCHAR(50),
)
CREATE TABLE ChiTietSanPham
(
	MaChiTietSanPham INT IDENTITY(1,1) PRIMARY KEY,
	MaSP NVARCHAR(10) FOREIGN KEY REFERENCES SanPham(MaSP),
	MaNCC VARCHAR(10) FOREIGN KEY REFERENCES NhaCungCap(MaNCC),
	MoTa NVARCHAR(100),
	ChiTiet NVARCHAR(100),
)

CREATE TABLE SanPham_NCC
(
	MaSP NVARCHAR(10) FOREIGN KEY REFERENCES SanPham(MaSP),
	MaNCC VARCHAR(10) FOREIGN KEY REFERENCES NhaCungCap(MaNCC),
	PRIMARY KEY(MaSP,MaNCC)
)
CREATE TABLE HoaDonNhap
(
	MaHDN VARCHAR(10) PRIMARY KEY NOT NULL,
	MaNCC VARCHAR(10) FOREIGN KEY REFERENCES NhaCungCap(MaNCC),
	NgayNhap DATE, 
)
CREATE TABLE ChiTietHoaDonNhap
(
	MaCTHDN NVARCHAR(10) PRIMARY KEY NOT NULL,
	MaHDN VARCHAR(10) FOREIGN KEY REFERENCES HoaDonNhap(MaHDN),
	MaSP NVARCHAR(10) FOREIGN KEY REFERENCES SanPham(MaSP),
	SoLuongNhap  INT, 
	Gia FLOAT,
	TongTienTra FLOAT,
)
CREATE TABLE KhachHang
(
	MaKH NVARCHAR(10) PRIMARY KEY NOT NULL,
	TenKH NVARCHAR(30),
	MaSoThe varchar(10),
	GioiTinh NVARCHAR(5),
	Diachi VARCHAR(30),
	Email VARCHAR(50), 
	SDT char(10),
)
CREATE TABLE HoaDon
(
	MaHD VARCHAR(10) PRIMARY KEY NOT NULL,
	TenKH NVARCHAR(100),
	DiaChi NVARCHAR(100),
	NgayMua DATETIME,
	TongGia FLOAT,
	SDT CHAR(11),
	DiaChiGiaoHang NVARCHAR(100),
    ThoiGianGiaoHang DATETIME,
	TrangThai NVARCHAR(30),
)
CREATE TABLE ChiTietHoaDon
(
	MaCTHD NVARCHAR(10) PRIMARY KEY NOT NULL,
	MaHD VARCHAR(10) FOREIGN KEY REFERENCES HoaDon(MaHD),
	MaSP NVARCHAR(10) FOREIGN KEY REFERENCES SanPham(MaSP),
	SoLuong INT,
	Size CHAR(3),
	TongGia FLOAT,
)